/**
 * Guests, groups, and seat assignment.
 *
 * A seat is addressed as `(elementId, seatIndex)` — seats are generated by
 * their table, never stored (ADR-0012). A guest holds that pair, or nothing.
 *
 * Guests are **not** document elements. They have no geometry, so putting them
 * in the element list would give the renderer, the spatial scan, and the undo
 * stack something to reason about that never appears on the plan
 * (ADR-0013).
 */

import type { ElementId } from '$lib/document/element';

export type GuestId = string;
export type GroupId = string;

/** Where a guest is sitting. `null` means unseated. */
export interface SeatRef {
  readonly elementId: ElementId;
  /** Zero-based index into the seats the table generates. */
  readonly seatIndex: number;
}

export interface Guest {
  readonly id: GuestId;
  readonly name: string;
  readonly email: string;
  /** Group this guest arrived with — a company, a household, a family. */
  readonly groupId: GroupId | null;
  /** The group's host sits first, and their seat decides where the group goes. */
  readonly isHost: boolean;
  readonly seat: SeatRef | null;

  /** Free-text meal choice, e.g. "Beef", "Vegetarian". */
  readonly meal: string;
  readonly dietary: string;
  /**
   * Accessibility need, e.g. "wheelchair", "hard of hearing".
   *
   * First-class rather than lumped into notes: it decides where someone can
   * physically sit, and it is the same conversation as the ADA clearances the
   * plan already checks.
   */
  readonly accessibility: string;
  readonly notes: string;

  /**
   * Stable key from the source data, for reconciling a re-import.
   *
   * A planner receives an updated list days before the event. Matching on this
   * rather than on the name is what keeps "Kate Brown" seated after she becomes
   * "Kate Brown-Smith" (ADR-0013).
   */
  readonly sourceKey: string;
}

export interface Group {
  readonly id: GroupId;
  readonly name: string;
  /** Groups the user wants kept whole even when it costs a better packing. */
  readonly keepTogether: boolean;
}

/** Two guests who must not share a table. */
export interface Separation {
  readonly a: GuestId;
  readonly b: GuestId;
  readonly reason: string;
}

export interface SeatingPlan {
  readonly guests: readonly Guest[];
  readonly groups: readonly Group[];
  readonly separations: readonly Separation[];
  /**
   * Locks assignments against re-import and auto-assign.
   *
   * Separate from an element's own `locked` flag: furniture still being moved
   * can have settled seating, and settled furniture can have open seating.
   */
  readonly assignmentsLocked: boolean;
}

export function createSeatingPlan(): SeatingPlan {
  return { guests: [], groups: [], separations: [], assignmentsLocked: false };
}

export function createGuest(id: GuestId, name: string, overrides: Partial<Guest> = {}): Guest {
  return {
    id,
    name,
    email: '',
    groupId: null,
    isHost: false,
    seat: null,
    meal: '',
    dietary: '',
    accessibility: '',
    notes: '',
    sourceKey: id,
    ...overrides,
  };
}

/* ------------------------------------------------------------------ *
 * Queries
 * ------------------------------------------------------------------ */

export function findGuest(plan: SeatingPlan, id: GuestId): Guest | undefined {
  return plan.guests.find((g) => g.id === id);
}

export function guestsAt(plan: SeatingPlan, elementId: ElementId): Guest[] {
  return plan.guests
    .filter((g) => g.seat?.elementId === elementId)
    .sort((a, b) => (a.seat?.seatIndex ?? 0) - (b.seat?.seatIndex ?? 0));
}

export function guestInSeat(
  plan: SeatingPlan,
  elementId: ElementId,
  seatIndex: number
): Guest | undefined {
  return plan.guests.find((g) => g.seat?.elementId === elementId && g.seat.seatIndex === seatIndex);
}

export function unseatedGuests(plan: SeatingPlan): Guest[] {
  return plan.guests.filter((g) => g.seat === null);
}

export function seatedCount(plan: SeatingPlan): number {
  return plan.guests.filter((g) => g.seat !== null).length;
}

export function groupMembers(plan: SeatingPlan, groupId: GroupId): Guest[] {
  const members = plan.guests.filter((g) => g.groupId === groupId);
  // The host first: their seat decides where the group goes.
  return [...members].sort((a, b) => Number(b.isHost) - Number(a.isHost));
}

export function groupHost(plan: SeatingPlan, groupId: GroupId): Guest | undefined {
  return plan.guests.find((g) => g.groupId === groupId && g.isHost);
}

/** Groups represented at a table, for a per-table summary. */
export function groupsAt(plan: SeatingPlan, elementId: ElementId): Group[] {
  const ids = new Set(guestsAt(plan, elementId).map((g) => g.groupId));
  return plan.groups.filter((group) => ids.has(group.id));
}

/* ------------------------------------------------------------------ *
 * Assignment
 * ------------------------------------------------------------------ */

/**
 * Seat a guest, displacing whoever was there.
 *
 * Displacement rather than refusal: dropping a guest onto an occupied seat is a
 * deliberate act, and refusing it silently leaves the user dragging at a seat
 * that never accepts them. The displaced guest becomes unseated and visible in
 * the unseated list rather than vanishing.
 */
export function seatGuest(plan: SeatingPlan, guestId: GuestId, seat: SeatRef): SeatingPlan {
  if (plan.assignmentsLocked) return plan;
  if (!findGuest(plan, guestId)) return plan;

  return {
    ...plan,
    guests: plan.guests.map((g) => {
      if (g.id === guestId) return { ...g, seat };
      const displaced = g.seat?.elementId === seat.elementId && g.seat.seatIndex === seat.seatIndex;
      return displaced ? { ...g, seat: null } : g;
    }),
  };
}

/**
 * Swap two guests' seats.
 *
 * Distinct from seating one onto the other, which would unseat them. Swapping
 * is what a user means when they drag one guest onto another.
 */
export function swapSeats(plan: SeatingPlan, a: GuestId, b: GuestId): SeatingPlan {
  if (plan.assignmentsLocked) return plan;

  const guestA = findGuest(plan, a);
  const guestB = findGuest(plan, b);
  if (!guestA || !guestB || a === b) return plan;

  return {
    ...plan,
    guests: plan.guests.map((g) => {
      if (g.id === a) return { ...g, seat: guestB.seat };
      if (g.id === b) return { ...g, seat: guestA.seat };
      return g;
    }),
  };
}

export function unseatGuest(plan: SeatingPlan, guestId: GuestId): SeatingPlan {
  if (plan.assignmentsLocked) return plan;
  return {
    ...plan,
    guests: plan.guests.map((g) => (g.id === guestId ? { ...g, seat: null } : g)),
  };
}

/** Unseat everyone at a table — clearing it without deleting the table. */
export function clearTable(plan: SeatingPlan, elementId: ElementId): SeatingPlan {
  if (plan.assignmentsLocked) return plan;
  return {
    ...plan,
    guests: plan.guests.map((g) => (g.seat?.elementId === elementId ? { ...g, seat: null } : g)),
  };
}

/**
 * Move everyone from one table to another, keeping seat indices.
 *
 * The operation the reference system needed and initially got wrong: it is
 * guests moving, not numbers changing, and it must be separate from applying a
 * numbering scheme (ADR-0013).
 */
export function moveTableGuests(
  plan: SeatingPlan,
  fromId: ElementId,
  toId: ElementId
): SeatingPlan {
  if (plan.assignmentsLocked || fromId === toId) return plan;

  return {
    ...plan,
    guests: plan.guests.map((g) => {
      if (g.seat?.elementId === fromId) return { ...g, seat: { ...g.seat, elementId: toId } };
      if (g.seat?.elementId === toId) return { ...g, seat: { ...g.seat, elementId: fromId } };
      return g;
    }),
  };
}

/**
 * Drop assignments that no longer point at a real seat.
 *
 * Run after any change to the plan's tables. Shrinking a table from ten seats
 * to eight leaves the guest in seat 9 pointing at nothing; deleting a table
 * leaves everyone at it dangling. They become **unseated rather than deleted**,
 * because a guest who quietly loses their seat is worse than one who was never
 * seated — and the caller is told how many, so the UI can say so.
 */
export function pruneAssignments(
  plan: SeatingPlan,
  seatCapacity: ReadonlyMap<ElementId, number>
): { plan: SeatingPlan; orphaned: Guest[] } {
  const orphaned: Guest[] = [];

  const guests = plan.guests.map((guest) => {
    if (!guest.seat) return guest;

    const capacity = seatCapacity.get(guest.seat.elementId);
    const stillValid = capacity !== undefined && guest.seat.seatIndex < capacity;
    if (stillValid) return guest;

    orphaned.push(guest);
    return { ...guest, seat: null };
  });

  return { plan: { ...plan, guests }, orphaned };
}

/* ------------------------------------------------------------------ *
 * Constraints
 * ------------------------------------------------------------------ */

/** Would seating these two together break a separation rule? */
export function areSeparated(plan: SeatingPlan, a: GuestId, b: GuestId): boolean {
  return plan.separations.some((s) => (s.a === a && s.b === b) || (s.a === b && s.b === a));
}

export interface SeatingConflict {
  readonly elementId: ElementId;
  readonly guests: readonly [GuestId, GuestId];
  readonly reason: string;
}

/** Separations currently violated by the seating as it stands. */
export function seatingConflicts(plan: SeatingPlan): SeatingConflict[] {
  const conflicts: SeatingConflict[] = [];

  for (const rule of plan.separations) {
    const a = findGuest(plan, rule.a);
    const b = findGuest(plan, rule.b);
    if (!a?.seat || !b?.seat) continue;
    if (a.seat.elementId !== b.seat.elementId) continue;

    conflicts.push({
      elementId: a.seat.elementId,
      guests: [a.id, b.id],
      reason: rule.reason,
    });
  }

  return conflicts;
}

/** Add a separation, ignoring duplicates and self-pairs. */
export function addSeparation(plan: SeatingPlan, a: GuestId, b: GuestId, reason = ''): SeatingPlan {
  if (a === b || areSeparated(plan, a, b)) return plan;
  return { ...plan, separations: [...plan.separations, { a, b, reason }] };
}

export function removeSeparation(plan: SeatingPlan, a: GuestId, b: GuestId): SeatingPlan {
  return {
    ...plan,
    separations: plan.separations.filter(
      (s) => !((s.a === a && s.b === b) || (s.a === b && s.b === a))
    ),
  };
}
